apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role #ClusterRole para replicar as permiss천es para todo o Cluster e n찾o mais por contexto
metadata:
  name: server-read
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #ClusterRoleBinding para replicar as permiss천es para todo o Cluster e n찾o mais por contexto
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: server
  namespace: prod
roleRef:
  kind: Role
  name: server-read
  apiGroup: rbac.authorization.k8s.io